### ISSUE TITLE
Render Tests: iOS failure of map-mode/tile-avoid-edges

### ISSUE THREAD

**Issue by stefankarschti** [maplibre/maplibre-native#1545]
![Image](https://github.com/maplibre/maplibre-native/assets/4198736/41eadfa9-55da-4b29-aef4-17a95bb6428d)

Expected:

![Image](https://github.com/maplibre/maplibre-native/assets/4198736/44a72114-6a3a-40c3-a31e-d15af13600fe)

**Comment by acalcutt** [comment]
for extra context, tile-avoid-edges and I have a history. haha
https://github.com/maplibre/maplibre-native/issues/479
https://github.com/maplibre/maplibre-native/pull/492

From what I've gathered, the first images is what it should look like now since https://github.com/maplibre/maplibre-native/commit/9ceb619940901d06909f7d6d0fc4a4e64572d228 , though I have never agreed with that...it should look more like the expected in my opinion. not sure is iOS had the same issue

**Comment by stefankarschti** [comment]
This is very good to know! Thank you!

**Comment by stefankarschti** [comment]
Actually the problem on my iOS device is that the red tile border is missing completely. But that's on the `topic/drawable-fixes` branch, part of the Metal implementation.

**Comment by sjg-wdw** [comment]
Have we fixed this one?

**Comment by stefankarschti** [comment]
The render test passes with this expected image:
![image](https://github.com/maplibre/maplibre-native/assets/4198736/e425ddc2-0cf7-4f46-afd4-3829c70c3e38)

[commit hash](https://github.com/maplibre/maplibre-native/commit/f6fb2d9c1a15a9279741dbe5f1c19635970d9fa4)
