### ISSUE TITLE
macOS Qt workflow failing `brew link` step

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre-native#1950]
cc @ntadej @mwilsnd 

https://github.com/maplibre/maplibre-native/actions/runs/7173052744/job/19532155978

```
==> Pouring python@3.12--3.12.1.ventura.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/2to3-3.12
Target /usr/local/bin/2to3-3.12
already exists. You may want to remove it:
  rm '/usr/local/bin/2to3-3.12'

To force the link and overwrite all conflicting files:
  brew link --overwrite python@3.12

To list all files that would be deleted:
  brew link --overwrite --dry-run python@3.12

Possible conflicting files are:
/usr/local/bin/2to3-3.12 -> /Library/Frameworks/Python.framework/Versions/3.12/bin/2to3-3.12
/usr/local/bin/idle3.12 -> /Library/Frameworks/Python.framework/Versions/3.12/bin/idle3.12
/usr/local/bin/pydoc3.12 -> /Library/Frameworks/Python.framework/Versions/3.12/bin/pydoc3.12
/usr/local/bin/python3.12 -> /Library/Frameworks/Python.framework/Versions/3.12/bin/python3.12
/usr/local/bin/python3.12-config -> /Library/Frameworks/Python.framework/Versions/3.12/bin/python3.12-config
```

We probably need to change that step to

```
  brew link --overwrite python@3.12
```

but maybe there is another solution that won't break with the next Python release.

**Comment by louwers** [comment]
It broke again. 🙉 

https://github.com/maplibre/maplibre-native/actions/runs/7572498541/job/20623131672?pr=2034

@ntadej Could you check if there is a more permanent solution? Maybe a hack where we query the most recent version?

**Comment by acalcutt** [comment]
I think I got around this in https://github.com/maplibre/maplibre-native/pull/2040 by commenting out that` brew link --overwrite python@3.11` line and letting it use the python already installed.

I had noticed when it was trying to install python, it was saying it already had a version of python installed, so it was trying to upgrade it. then at the end it tried to make a symlink, which failed because it already existed (the 'brew link' error)
`python@3.11 3.11.7 is already installed but outdated (so it will be upgraded).`
