### ISSUE TITLE
Documentation update for iOS v6.0.0

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre-native#2069]
https://maplibre.org/maplibre-native/ios/api/ is still at version 5. @louwers can you update it to v6?

**Comment by louwers** [comment]
Unfortunetely we cannot use Jazzy anymore, because it needs a project that is built with Xcode (we use Bazel now).

I want to generate documentation with DocC but for that we are blocked by an upstream issue: there is a Bazel rule to generate documentation with DocC but it only works for Swift projects (not Objective-C). https://github.com/bazelbuild/rules_apple/issues/2241

I'll ask on the Bazel Slack if they have any ideas, they tend to be very helpful. Maybe @keith has any ideas.

**Comment by louwers** [comment]
Related: https://github.com/maplibre/maplibre-native/issues/1158

**Comment by keith** [comment]
blah yea, short of implementation that docc issue I don't know of a workaround

**Comment by louwers** [comment]
I will try the steps from https://forums.swift.org/t/clang-support-for-objective-c-symbol-graph-generation/57689 manually.

**Comment by louwers** [comment]
I think I can get something to build with a manual script!

<img width="1552" alt="image" src="https://github.com/maplibre/maplibre-native/assets/649392/5a6b8b81-ed37-45ba-a4fd-258abb25385e">
