### ISSUE TITLE
Fix flakiness Android Instrumentation Tests

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre-native#2248]
I would like to run the Android instrumentation tests as part of the PR workflows.

There are some flakiness issues.

1. https://github.com/maplibre/maplibre-native/issues/2187

2. This happens sometimes:

```
java.lang.IllegalArgumentException: Could not find layer Streets
at org.maplibre.android.maps.Style.getPredefinedStyle(Style.java:1430)
at org.maplibre.android.testapp.activity.espresso.PixelTestActivity.onMapReady(PixelTestActivity.kt:29)
```

3. Precision when comparing floats should be reduced in a few places.

**Comment by kocheick** [comment]
I'm experimenting the same error as I'm looking to update the plugins from maplibre-android-plugins repository to use MapLibre instead of Mapbox.
Most (99%) of the code/packages have been renamed to MapLibre but when I run the **Tests** to make sure all is well: many tests pass fine but some throw this particular exception :  java.lang.IllegalArgumentException: Could not find layer Streets

**Comment by louwers** [comment]
They have been running very consistently the past few months.
