### ISSUE TITLE
[IOS] Snapshotter crash in release version 5.13.0-pre.1

### ISSUE THREAD

**Issue by davidmtamas** [maplibre/maplibre-native#243]
We at Bikemap use MapLibre extensively and are developing on M1 machines, therefore we use [version 5.13.0-pre.1](https://github.com/maplibre/maplibre-gl-native-distribution/releases/tag/5.13.0-pre.1) with Metal support in our app.

We use the Snapshotting functionality in one of our apps features and we noticed crashes occurring randomly on many map styles and coordinates. We tried to upgrade MetalANGLE framework used by MapLibre but the upgrade didn't mitigate the crashes.

We managed to create a demo project which reliably crashes with a map style set to a specific coordinate. We are aware that the release notes of the aforementioned build contain failing tests for the Snapshotter, so we thought providing a sample project would help with tracking down the root issues.

[MapLibreSnapshotterDemo 2.zip](https://github.com/maplibre/maplibre-gl-native/files/8115937/MapLibreSnapshotterDemo.2.zip)

**Comment by birkskyum** [comment]
is this still the case?

**Comment by hactar** [comment]
Yes this issue persists. It instantly occurs on the iOS 15 simulator. On the iOS 16 simulator if you push the button the demo app, it takes about 15-30 seconds to crash instead of crashing instantly like with iOS 15, but it still does crash.
<img width="1820" alt="Screenshot 2022-09-21 at 13 08 50" src="https://user-images.githubusercontent.com/645674/191489250-d931aefb-e062-4d86-81f8-49a12d3c88ed.png">

**Comment by birkskyum** [comment]
Thanks for the update @hactar

**Comment by louwers** [comment]
We now have Metal support with the new rendering architecture. See https://github.com/maplibre/maplibre-native/issues/1609

Please try out the pre-release and create a new issue if you run into something not working as expected.
