### ISSUE TITLE
Replace usage of `android.os.AsyncTask` with Kotlin Coroutines

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre-native#2436]
As mentioned by @westnordost in [this comment](https://github.com/maplibre/maplibre-native/issues/2432#issuecomment-2132178993) [AsyncTask](https://developer.android.com/reference/android/os/AsyncTask) is deprecated and we should replace our usage of it with more modern APIs like Kotlin Coroutines.

A [developer](https://maplibre.org/jobs/developer-job-posting/) could claim a bounty under the [modernization](https://github.com/maplibre/maplibre/issues/270) bounty direction for this work.

The source files using `android.os.AsyncTask` should also be converted to Kotlin.

**Comment by westnordost** [comment]
Five cents from a developer using Kotlin: Migrating to Kotlin coroutines is something that should not be done in isolation only to replace `AsyncTask`s but in concert with generally changing also the API to use suspending functions rather than callback-based functions. I am not sure how suspending APIs translate to Java code on the surface, though. _Maybe_, from the point of view of Java code, suspending functions look like functions with a callback parameter?

With Kotlin's suspending functions, the API to initialize the map could look like this (as if it were blocking calls, but they aren't), instead of juggling with callbacks:
```kotlin
suspend fun initMap() {
  val map = mapView.getMap()
  val style = map.setStyle("mapstyle.json")
  style.addImage("someImg", getDrawable(R.drawable.someImg))
  // ...
}
```

In fact, what I did was to write extension functions to wrap the calls for my use into a suspending API to profit of this convenience myself. E.g.
```kotlin

suspend fun MapView.awaitGetMap(): MapLibreMap = suspendCoroutine { cont ->
    getMapAsync { cont.resume(it) }
}
```
To make a blocking API that has no callback suspending, one would e.g.

```kotlin

suspend fun Style.awaitAddImage(name: String, bitmap: Bitmap) { 
    withContext(IO) { addImage(name, bitmap) }
}
```

**Comment by tarkvara** [comment]
I believe all these _AsyncTask_ calls were removed as part of issue 1607.  I do see a couple of _AsyncTask_ calls, but only in Java code, not Kotlin… not sure where that Java code is actually used.

**Comment by louwers** [comment]
This bounty can be paid out, PR is ready but we should hold off merging for a bit because it is a breaking change.
