### ISSUE TITLE
Incorrect rendering of extruded geometry

### ISSUE THREAD

**Issue by alasram** [maplibre/maplibre-native#2591]
Android release android-v11.0.1 (also 11.0) shows artifacts when rendering extruded geometry (such as buildings).
The issue is only seen in the drawable GL renderer. Teh legacy GL renderer does not have the issue:
![angle3](https://github.com/maplibre/maplibre-native/assets/5223673/d701efc1-e1c1-4287-8c1a-fec994ef648c)
![angle2](https://github.com/maplibre/maplibre-native/assets/5223673/4b631eef-029a-476b-8987-7f354c6b7589)
![angle1](https://github.com/maplibre/maplibre-native/assets/5223673/dacd93ec-ddd7-4028-8f70-0d73e90a7c64)

The bad geometry is camera dependent

**To Reproduce**
- Run on Android devices with a map that has 2.5D geometry data
- Make sure MapLibreAndroid-drawable library is used
- Zoom into the geometry and navigate the map to see incorrect culled geometry along a line
-  Issue not present when switching to MapLibreAndroid-legacy library

**Comment by alasram** [comment]
Issue related to geometry clipping at tile boundaries
![1](https://github.com/maplibre/maplibre-native/assets/5223673/4ca8a49d-2534-455e-9efa-944092456ed5)
![2](https://github.com/maplibre/maplibre-native/assets/5223673/b68ce5da-d909-4e9a-bd8b-177ee470be58)
![3](https://github.com/maplibre/maplibre-native/assets/5223673/809f9e3d-951a-4e79-a141-6685ae238b0a)
![4](https://github.com/maplibre/maplibre-native/assets/5223673/bf216a2a-667e-4b15-9bbe-bda3c87b4f8e)

**Comment by louwers** [comment]
Oh yes I have noticed this too!

**Comment by sjg-wdw** [comment]
If it's a regression from the previous version, yes.  We can look into it.

**Comment by alasram** [comment]
@sjg-wdw did your team look into this by any chance? This is currently the only blocker for us to move from the legacy to the drawable renderer

**Comment by sjg-wdw** [comment]
What does this suggest to you @TimSylvester

**Comment by TimSylvester** [comment]
I'd guess a depth issue.  We tested that quite a bit, so it might be a more recent regression.

Is it in a specific area, only at a certain angle, etc?  I see some "seams" but that looks more like a precision problem.

![RPReplay_Final1725548657](https://github.com/user-attachments/assets/2fcbc8be-dfb2-4792-916b-9f425353271c)

**Comment by louwers** [comment]
I think I have been seeing this for a while.

**Comment by sjg-wdw** [comment]
Might be worth doing a regression search.  If it appeared at a certain commit that would be simpler.

**Comment by TimSylvester** [comment]
Assuming this is the same thing, it's not tile boundaries, just internal faces I guess?

![RPReplay_Final1725633046](https://github.com/user-attachments/assets/cea977c8-7291-4f11-bf8c-3277a309752a)

**Comment by TimSylvester** [comment]
So the way this works is that everything is drawn twice, the first time accumulating the nearest depth value to capture the nearest faces, then drawn to the framebuffer but only where the fragment matches that depth value.  When the extrusion is translucent, this second pass also populates the stencil buffer with a unique value which prevents other tiles from drawing over it, so that nothing is blended twice.

For that to work correctly, all the tiles need to be drawn in the depth pass before any tiles are drawn in the color pass.  So the regression seems to be that the drawable ordering changed.

<img width="400" alt="image" src="https://github.com/user-attachments/assets/dba4a773-c9a8-4449-bd12-f25cce5cabef">

<img width="400" alt="image" src="https://github.com/user-attachments/assets/d66a8999-0714-4735-bc22-adfacfeb6350">

<img width="400" alt="image" src="https://github.com/user-attachments/assets/d694cf71-f016-4075-99dd-17f2a740c368">

<img width="400" alt="image" src="https://github.com/user-attachments/assets/e8b02c00-1138-4332-bb3b-8f0d45848391">
