### ISSUE TITLE
Metal: Incorrect reuse of sprites for line-pattern

### ISSUE THREAD

**Issue by chchrn** [maplibre/maplibre-native#2735]
**Describe the bug**

In our product we use a style with `line-pattern`. In versions that use MetalKit for map rendering we noticed a problem with filling lines with pattern. 

I have prepared a test project demonstrating the problem (attached). 

The project style is available in style.json file or at https://api.npoint.io/7dac9318bfb95b18a9dc.

The example uses a simple geojson with two lines, one should be filled with a black dashed line and the other with yellow icons. 

On a small zoom everything shows up as it should, but if you zoom in on the map you can see that the styles get mixed up. 
The yellow line starts to appear as a black dashed line and vice versa. 

The problem seems to be the reuse of sprites.

We have only noticed this problem for the `line-pattern` property.

Before using the pre-metalKit version, we had no problems. The problem persists on the latest version 6.5.4 , and is also definitely present on 6.5.0

[MlnPatterBug.zip](https://github.com/user-attachments/files/16662818/MlnPatterBug.zip)

**Screenshots**
![photo_2024-08-19 19 10 45](https://github.com/user-attachments/assets/0a18ed3b-ad57-4bf0-9fca-5593badd387a)
![photo_2024-08-19 19 10 47](https://github.com/user-attachments/assets/469c72d9-e4e2-4a62-b299-53c23435cda6)
![photo_2024-08-19 19 10 50](https://github.com/user-attachments/assets/198595eb-0e23-466c-9a9f-51cedd90886f)

**Platform information (please complete the following information):**
 - OS: iOS
 - Platform: iOS
 - Version: 6.5.4

**Comment by louwers** [comment]
Thanks for the bug report. I'll have a look if I can create a render test for this.

**Comment by moodstubos** [comment]
We have the same problem with current Android release: [android-v11.1.0](https://github.com/maplibre/maplibre-native/releases/tag/android-v11.1.0)

**Comment by sjg-wdw** [comment]
@alexcristici see if you can fix this and ideally create a test for it.

**Comment by chchrn** [comment]
@alexcristici how can I help with finding the bug? Do you have any idea what the bug might be?

**Comment by alexcristici** [comment]
@chchrn I'm investigating the `pattern_from` and `pattern_to` data driven attribute buffers.

**Comment by iwo** [comment]
This issue is probably a root cause of https://github.com/maplibre/maplibre-native/issues/2621

It can easily be reproduced on Android (both real device and emulator) using the minimalistic sample style provided above.

@TimSylvester I see you recently worked on `LineLayerTweaker`, maybe you could help with this bug?

**Comment by TimSylvester** [comment]
I don't think it's just the pattern coordinates getting mixed up, the geometry seems to be wrong.  Somehow a drawable is ending up with positions, and their matching texture coordinates, from both lines.  I think that points to a problem in the bucket.

Since this is happening on Android, I take that to mean it isn't specific to `MLN_TRIANGULATE_FILL_OUTLINES` being enabled.

<img width="500" alt="image" src="https://github.com/user-attachments/assets/8f619c83-80e0-475e-af11-eae7eee6dc13">

**Comment by iwo** [comment]
Great! The fix resolved our issues 🎉 

@louwers what's your release schedule i.e. when will the fix go live?

**Comment by iwo** [comment]
Hi @louwers, I see you made a release of Android v10 branch but I don't see `android-v11.5.2`. Are you planning to make it soon? Is there some there some problem with making this release?

**Comment by louwers** [comment]
There is no problem, releases are made when they are requested. Happy to make a release for Android with this fix as well.

**Comment by iwo** [comment]
It would be great if you could make it then :-)
We keep getting reports from prod users about this issue.

**Comment by louwers** [comment]
Will be released later today.

**Comment by louwers** [comment]
There was an issue with the release @iwo, but it is out now.
