### ISSUE TITLE
Remove duplicated package.json

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre-native#657]
https://github.com/maplibre/maplibre-gl-native/blob/main/package.json

https://github.com/maplibre/maplibre-gl-native/blob/main/platform/ios/package.json

These are almost the same and should be deduplicated. Need to check if the second one is still being used.

**Comment by birkskyum** [comment]
The js scripts we have are mainly for pulling in render tests and shaders from maplibre-gl-native. It's mainly the package.json in the root along with the files in /scripts that are in use. Many of the files in /scripts needs to be updated from es5 to typescript so they can be run with ts-node - they are not working currently because they require() a lot of packages that are only built as es modules, so they need import/export syntax instead.

**Comment by louwers** [comment]
I think the iOS one is just an outdated version of the other one.
