### ISSUE TITLE
xvfb causes flaky Linux tests

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre-native#720]
Node.js CI is (sometimes) failing due to "Failed to open X display", see for example:

- https://github.com/maplibre/maplibre-gl-native/pull/716/checks
- https://github.com/maplibre/maplibre-gl-native/actions/runs/3985516173/jobs/6832980335

@ntadej on Slack:

> This has been failing for a while. It’s not a node specific thing. I suspect a race condition when setting up the fake display.

**Comment by acalcutt** [comment]
a while back a lot of the tests got changed to only run on the macos runner because those runners had X server and didn't require xvfb-run. no one ever figured out the cause, the tests just got moved to macos.

I wonder if maybe pre-starting xvfb with something like
`/usr/bin/Xvfb :99 -screen 0 1024x768x24 -ac +extension GLX +render -noreset`
( I use this run my [xvfb](https://github.com/acalcutt/wifidb-tileserver-gl/blob/master/tileserver-gl/systemd/Xvfb.service#L10) for [tileserver](https://github.com/acalcutt/wifidb-tileserver-gl/blob/master/tileserver-gl/systemd/Tileserver.service#L9) using systemd)

**Comment by louwers** [comment]
@acalcutt Maybe we can try using this? https://github.com/marketplace/actions/gabrielbb-xvfb-action

**Comment by acalcutt** [comment]
I'm not familiar with it, but it looks like it would work

**Comment by louwers** [comment]
xvfb is included in the latest Ubuntu image:

https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md

**Comment by acalcutt** [comment]
Even if it is included it still has to be started i believe, like I mentioned with

/usr/bin/Xvfb :99 -screen 0 1024x768x24 -ac +extension GLX +render -noreset
(setting the DISPLAY environment variable)

xvfb-run also starts Xvfb (like we have now)

**Comment by acalcutt** [comment]
Also, just FYI, changing the OS these run on changes the compatibility of the binaries we are generating for node. I'm not opposed to moving the binaries to 22.04, just wanted to note that, since it requires changes for anyone using those binaries ( a different OS)

I brought that up a bit here https://osmus.slack.com/archives/C02B2CBSNBU/p1670899965718649

**Comment by acalcutt** [comment]
I do see this thread on the action you mentioned. sounds similar to what happens here where it doesn't find X sporadically https://github.com/GabrielBB/xvfb-action/issues/22

**Comment by acalcutt** [comment]
I tested https://github.com/marketplace/actions/gabrielbb-xvfb-action .. You can see when it runs it is using the same xvfb-run command in the background...so I doubt it is going to help

```
Run GabrielBB/xvfb-action@v1
/usr/bin/sudo apt-get install -y xvfb
Reading package lists...
Building dependency tree...
Reading state information...
xvfb is already the newest version (2:1.20.13-1ubuntu1~20.04.5).
0 upgraded, 0 newly installed, 0 to remove and 1[9](https://github.com/maplibre/maplibre-gl-native/actions/runs/3993660243/jobs/6850577880#step:16:10) not upgraded.
Command: npm test
/usr/bin/xvfb-run --auto-servernum npm test
```
