### ISSUE TITLE
Investigate configuring Xcode with Bazel

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre-native#840]
Anagolous to #737, I would like to investigate if configuring Xcode with Bazel is a vaiable option.

The Bazel setup donated by Lyft & @nvanfleet seems a lot more solid than the CMake based iOS build setup in its current form.

There is also a quite widely used ruleset for generating Xcode projects with Bazel: https://github.com/buildbuddy-io/rules_xcodeproj

**Comment by louwers** [comment]
I am hitting this issue when trying to write a config to build the app

https://github.com/bazelbuild/bazel/issues/9429

And this issue when generating an Xcode config for the framework:

https://github.com/buildbuddy-io/rules_xcodeproj/issues/1768

**Comment by ntadej** [comment]
Should we maybe have a technical chat at some point, because we need to figure out what are the actual limitations of CMake.

What I would actually propose is to use CMake to generate the Xcode project, but then some other higher-level tool to use it to build the frameworks (potentially also Bazel).

**Comment by louwers** [comment]
I replied in the other thread.

`@import`s within Objective-C [are not yet supported by Bazel](https://github.com/bazelbuild/bazel/issues/9429), which the iosapp target uses:

**Comment by keith** [comment]
From the Lyft perspective the value of using bazel wasn't because cmake was bad but just because that made it easier to integrate with our internal app's build which uses bazel.

I do think you should be able to get rules_xcodeproj working and you could use that locally. Given the very few uses of `@import` I would just swap them with the old style. There shouldn't be a practical downside for this use case and IIRC cmake doesn't support those by default either.

**Comment by louwers** [comment]
@keith Thanks for pitching in. Switching to the angled bracket notation for the test app is a good idea, although importing an Objective-C library from another also seems problematic: https://github.com/bazelbuild/bazel/issues/9461

**Comment by keith** [comment]
it should be ok with the right `includes`
