### ISSUE TITLE
Run Windows build on CI with MBGL_EGL = ON

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre-native#917]
We have a regression because some files were not compiled on CI.

If someone could look into making sure we compile these files on CI, that would prevent regressions in the future.

This is the file in question (there might be more).

```
platform/windows/src/headless_backend_egl.cpp
```

**Comment by louwers** [comment]
Note CI is also not running: https://github.com/maplibre/maplibre-gl-native/pull/918

**Comment by acalcutt** [comment]
How would you want to do this? It would need to be built with different options since the default node build has MBGL_EGL=OFF . We would have to add the -DMBGL_EGL=OFF option to the configure step ( https://github.com/maplibre/maplibre-gl-native/blob/main/.github/workflows/node-ci.yml#L163-L169 ) , and if we did that it wouldn't test the non-EGL mode.

I could maybe add a variable to the matirix and add a few more os runs.... or maybe maybe a copy of this ci that runs an EGL build...

**Comment by acalcutt** [comment]
I think ci don't run on that PR because the paths are restricted and don't include the windows/linux/macos playform.
https://github.com/maplibre/maplibre-gl-native/blob/main/.github/workflows/node-ci.yml#L30-L45

**Comment by etnav** [comment]
Flag is called `MBGL_WITH_EGL`, was a typo I made :smile:
